import {
  BarChart3,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Cpu,
  Folder,
  GraduationCap,
  Handshake,
  Lightbulb,
  Megaphone,
  Monitor,
  RefreshCw,
  Shield,
  Smartphone,
  Target,
  TrendingUp,
  Users,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  briefcase: Briefcase,
  target: Target,
  users: Users,
  'trending-up': TrendingUp,
  'bar-chart': BarChart3,
  building: Building2,
  smartphone: Smartphone,
  shield: Shield,
  monitor: Monitor,
  'refresh-cw': RefreshCw,
  calendar: Calendar,
  lightbulb: Lightbulb,
  folder: Folder,
  cpu: Cpu,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  handshake: Handshake,
  megaphone: Megaphone,
}

export const iconOptions = [
  { label: 'Briefcase', value: 'briefcase' },
  { label: 'Target', value: 'target' },
  { label: 'Users', value: 'users' },
  { label: 'Trending Up', value: 'trending-up' },
  { label: 'Bar Chart', value: 'bar-chart' },
  { label: 'Building', value: 'building' },
  { label: 'Smartphone', value: 'smartphone' },
  { label: 'Shield', value: 'shield' },
  { label: 'Monitor', value: 'monitor' },
  { label: 'Refresh', value: 'refresh-cw' },
  { label: 'Calendar', value: 'calendar' },
  { label: 'Lightbulb', value: 'lightbulb' },
  { label: 'Folder', value: 'folder' },
  { label: 'Cpu', value: 'cpu' },
  { label: 'Graduation Cap', value: 'graduation-cap' },
  { label: 'Book Open', value: 'book-open' },
  { label: 'Handshake', value: 'handshake' },
  { label: 'Megaphone', value: 'megaphone' },
]
