/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    updates: Update;
    media: Media;
    categories: Category;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    updates: UpdatesSelect<false> | UpdatesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    homepage: Homepage;
    'about-page': AboutPage;
    'progress-page': ProgressPage;
    'updates-page': UpdatesPage;
    'get-involved-page': GetInvolvedPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'progress-page': ProgressPageSelect<false> | ProgressPageSelect<true>;
    'updates-page': UpdatesPageSelect<false> | UpdatesPageSelect<true>;
    'get-involved-page': GetInvolvedPageSelect<false> | GetInvolvedPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates".
 */
export interface Update {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  image: number | Media;
  date: string;
  category: 'announcements' | 'events' | 'statements' | 'media';
  excerpt: string;
  content?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'updates';
        value: number | Update;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates_select".
 */
export interface UpdatesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  image?: T;
  date?: T;
  category?: T;
  excerpt?: T;
  content?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: number | Media;
  navItems?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo: number | Media;
  tagline: string;
  /**
   * Optional second line shown below the main tagline.
   */
  secondaryTagline?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    /**
     * Displayed text, e.g. (242) 327-1530
     */
    phoneLabel?: string | null;
    /**
     * e.g. tel:+12423271530
     */
    phoneHref?: string | null;
    /**
     * Displayed text, e.g. 1-800-123-4567
     */
    tollFreeLabel?: string | null;
    /**
     * e.g. tel:+18001234567
     */
    tollFreeHref?: string | null;
    email?: string | null;
    address?: string | null;
  };
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The year is prepended automatically — e.g. entering "MIND. All rights reserved." renders "© 2026 MIND. All rights reserved."
   */
  copyrightText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    /**
     * Press Enter for a new line. Example: "Building today what" on line 1, "The Bahamas needs to win tomorrow." on line 2.
     */
    title: string;
    subtitle: string;
    primaryCTA: {
      label: string;
      href: string;
    };
    secondaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
    backgroundImages?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
    backgroundImageInterval?: number | null;
  };
  showYou: {
    heading: string;
    description: string;
    cta: {
      label: string;
      href: string;
    };
    cards?:
      | {
          title: string;
          /**
           * e.g. LIVE, COMING, IN PROGRESS
           */
          label: string;
          labelColor: 'green' | 'blue' | 'orange';
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  ministryBuilt: {
    heading: string;
    description?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
    button: {
      label: string;
      href: string;
    };
  };
  ministerProfile: {
    label: string;
    name: string;
    title: string;
    bio?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  initiatives: {
    heading: string;
    cta: {
      label: string;
      href: string;
    };
    cards?:
      | {
          icon: 'briefcase' | 'target' | 'users' | 'trending-up';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  governmentService: {
    heading: string;
    description: string;
    cta: {
      label: string;
      href: string;
    };
    images: {
      family: number | Media;
      laptop: number | Media;
      celebrating: number | Media;
    };
  };
  drawThreads: {
    heading: string;
    description: string;
    tags?:
      | {
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
    cta: {
      label: string;
      href: string;
    };
  };
  countryFuture: {
    /**
     * Use a new line to force a line break.
     */
    heading: string;
    subtitle: string;
    primaryButton: {
      label: string;
      href: string;
    };
    secondaryButton?: {
      label?: string | null;
      href?: string | null;
    };
  };
  meta?: {
    /**
     * Shown in the browser tab and as the clickable headline in search results. Falls back to the default page title if left blank.
     */
    title?: string | null;
    /**
     * Shown under the title in search results. Aim for roughly 150-160 characters. Falls back to the default description if left blank.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    /**
     * Press Enter for a new line. Example: "A new Ministry." on line 1, "A clear mandate." on line 2.
     */
    title: string;
    subtitle?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  textImageSections?:
    | {
        heading: string;
        text?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        image: number | Media;
        imagePosition?: ('left' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  mission: {
    heading: string;
    description: string;
    cards?:
      | {
          icon:
            | 'briefcase'
            | 'target'
            | 'users'
            | 'trending-up'
            | 'bar-chart'
            | 'building'
            | 'smartphone'
            | 'shield'
            | 'monitor'
            | 'refresh-cw'
            | 'calendar'
            | 'lightbulb'
            | 'folder'
            | 'cpu'
            | 'graduation-cap'
            | 'book-open'
            | 'handshake'
            | 'megaphone';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  dualCta: {
    first: {
      heading: string;
      description: string;
      button: {
        label: string;
        href: string;
      };
    };
    second: {
      heading: string;
      description: string;
      button: {
        label: string;
        href: string;
      };
    };
  };
  policyAreas: {
    heading: string;
    cta: {
      label: string;
      href: string;
    };
    policies?:
      | {
          label: string;
          status: 'active' | 'comingSoon';
          href?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  departments: {
    heading: string;
    description: string;
    items?:
      | {
          icon:
            | 'briefcase'
            | 'target'
            | 'users'
            | 'trending-up'
            | 'bar-chart'
            | 'building'
            | 'smartphone'
            | 'shield'
            | 'monitor'
            | 'refresh-cw'
            | 'calendar'
            | 'lightbulb'
            | 'folder'
            | 'cpu'
            | 'graduation-cap'
            | 'book-open'
            | 'handshake'
            | 'megaphone';
          title: string;
          description: string;
          linkLabel: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  ministerProfiles?:
    | {
        label: string;
        name: string;
        title: string;
        bio?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  countryFuture: {
    heading: string;
    subtitle: string;
    primaryButton: {
      label: string;
      href: string;
    };
    secondaryButton?: {
      label?: string | null;
      href?: string | null;
    };
  };
  meta?: {
    /**
     * Shown in the browser tab and as the clickable headline in search results. Falls back to the default page title if left blank.
     */
    title?: string | null;
    /**
     * Shown under the title in search results. Aim for roughly 150-160 characters. Falls back to the default description if left blank.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress-page".
 */
export interface ProgressPage {
  id: number;
  status: {
    heading: string;
    description: string;
    cards?:
      | {
          title: string;
          description: string;
          icon:
            | 'briefcase'
            | 'target'
            | 'users'
            | 'trending-up'
            | 'bar-chart'
            | 'building'
            | 'smartphone'
            | 'shield'
            | 'monitor'
            | 'refresh-cw'
            | 'calendar'
            | 'lightbulb'
            | 'folder'
            | 'cpu'
            | 'graduation-cap'
            | 'book-open'
            | 'handshake'
            | 'megaphone';
          /**
           * Hex color, e.g. #16A34A
           */
          color: string;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  modernizeGovernment: {
    title: string;
    description: string;
    cards?:
      | {
          icon:
            | 'briefcase'
            | 'target'
            | 'users'
            | 'trending-up'
            | 'bar-chart'
            | 'building'
            | 'smartphone'
            | 'shield'
            | 'monitor'
            | 'refresh-cw'
            | 'calendar'
            | 'lightbulb'
            | 'folder'
            | 'cpu'
            | 'graduation-cap'
            | 'book-open'
            | 'handshake'
            | 'megaphone';
          label: string;
          labelColor: 'green' | 'blue' | 'orange' | 'dark' | 'planned';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  buildFutureReadiness: {
    title: string;
    description: string;
    cards?:
      | {
          icon:
            | 'briefcase'
            | 'target'
            | 'users'
            | 'trending-up'
            | 'bar-chart'
            | 'building'
            | 'smartphone'
            | 'shield'
            | 'monitor'
            | 'refresh-cw'
            | 'calendar'
            | 'lightbulb'
            | 'folder'
            | 'cpu'
            | 'graduation-cap'
            | 'book-open'
            | 'handshake'
            | 'megaphone';
          label: string;
          labelColor: 'green' | 'blue' | 'orange' | 'dark' | 'planned';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  developBahamianTalent: {
    title: string;
    description: string;
    backgroundImage: number | Media;
    cards?:
      | {
          icon:
            | 'briefcase'
            | 'target'
            | 'users'
            | 'trending-up'
            | 'bar-chart'
            | 'building'
            | 'smartphone'
            | 'shield'
            | 'monitor'
            | 'refresh-cw'
            | 'calendar'
            | 'lightbulb'
            | 'folder'
            | 'cpu'
            | 'graduation-cap'
            | 'book-open'
            | 'handshake'
            | 'megaphone';
          label: string;
          labelColor: 'green' | 'blue' | 'orange' | 'dark' | 'planned';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  driveNationalDevelopment: {
    title: string;
    description: string;
    cards?:
      | {
          icon:
            | 'briefcase'
            | 'target'
            | 'users'
            | 'trending-up'
            | 'bar-chart'
            | 'building'
            | 'smartphone'
            | 'shield'
            | 'monitor'
            | 'refresh-cw'
            | 'calendar'
            | 'lightbulb'
            | 'folder'
            | 'cpu'
            | 'graduation-cap'
            | 'book-open'
            | 'handshake'
            | 'megaphone';
          label: string;
          labelColor: 'green' | 'blue' | 'orange' | 'dark' | 'planned';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  countryFuture: {
    heading: string;
    subtitle: string;
    pillarsHeading?: string | null;
    pillarsDescription?: string | null;
    footerText?: string | null;
    primaryButton: {
      label: string;
      href: string;
    };
  };
  meta?: {
    /**
     * Shown in the browser tab and as the clickable headline in search results. Falls back to the default page title if left blank.
     */
    title?: string | null;
    /**
     * Shown under the title in search results. Aim for roughly 150-160 characters. Falls back to the default description if left blank.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates-page".
 */
export interface UpdatesPage {
  id: number;
  hero: {
    title: string;
    subtitle: string;
  };
  closing: {
    heading: string;
    subtitle: string;
    primaryButton: {
      label: string;
      href: string;
    };
  };
  meta?: {
    /**
     * Shown in the browser tab and as the clickable headline in search results. Falls back to the default page title if left blank.
     */
    title?: string | null;
    /**
     * Shown under the title in search results. Aim for roughly 150-160 characters. Falls back to the default description if left blank.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-page".
 */
export interface GetInvolvedPage {
  id: number;
  hero: {
    title: string;
    subtitle?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  categoriesSection: {
    heading: string;
    categories?:
      | {
          icon:
            | 'briefcase'
            | 'target'
            | 'users'
            | 'trending-up'
            | 'bar-chart'
            | 'building'
            | 'smartphone'
            | 'shield'
            | 'monitor'
            | 'refresh-cw'
            | 'calendar'
            | 'lightbulb'
            | 'folder'
            | 'cpu'
            | 'graduation-cap'
            | 'book-open'
            | 'handshake'
            | 'megaphone';
          image: number | Media;
          title: string;
          description: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  form: {
    formTitle: string;
    illustrationImage: number | Media;
    /**
     * Configure where form submissions are sent. SendGrid API credentials stay in server environment variables.
     */
    notifications: {
      /**
       * Inbox that receives Get Involved form submissions.
       */
      notificationEmail: string;
      /**
       * Customize the notification email content. Use {{name}}, {{email}}, {{category}}, and {{message}} as placeholders. The HTML email is styled automatically to match the MIND website.
       */
      emailTemplate?: {
        /**
         * Shown in the email header. Prefer PNG or JPG (email clients often block SVG). If empty, the Header logo is used.
         */
        logo?: (number | null) | Media;
        subject?: string | null;
        heading?: string | null;
        /**
         * Used for the plain-text version of the email. The HTML version uses the branded MIND layout automatically.
         */
        body?: string | null;
        /**
         * Optional footer text shown at the bottom of the email.
         */
        footer?: string | null;
      };
      /**
       * Shown to visitors after a successful form submission.
       */
      successMessage?: string | null;
    };
  };
  reachOut: {
    heading: string;
    text?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    button?: {
      label?: string | null;
      href?: string | null;
    };
    image: number | Media;
    imagePosition?: ('left' | 'right') | null;
  };
  followTheWork: {
    heading: string;
    description: string;
    backgroundImage: number | Media;
    socialLinks?:
      | {
          platform: 'facebook' | 'instagram' | 'linkedin' | 'tiktok';
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    /**
     * Shown in the browser tab and as the clickable headline in search results. Falls back to the default page title if left blank.
     */
    title?: string | null;
    /**
     * Shown under the title in search results. Aim for roughly 150-160 characters. Falls back to the default description if left blank.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    title: string;
    subtitle: string;
    secondaryCTA?: {
      label?: string | null;
      href?: string | null;
    };
  };
  officeInfo: {
    address: string;
    phone: string;
    email: string;
    hours?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
  };
  enquiries?:
    | {
        icon:
          | 'briefcase'
          | 'target'
          | 'users'
          | 'trending-up'
          | 'bar-chart'
          | 'building'
          | 'smartphone'
          | 'shield'
          | 'monitor'
          | 'refresh-cw'
          | 'calendar'
          | 'lightbulb'
          | 'folder'
          | 'cpu'
          | 'graduation-cap'
          | 'book-open'
          | 'handshake'
          | 'megaphone';
        title: string;
        description: string;
        email: string;
        id?: string | null;
      }[]
    | null;
  followUs: {
    heading: string;
    subtitle: string;
    socialLinks?:
      | {
          platform: 'facebook' | 'instagram' | 'linkedin' | 'tiktok';
          label: string;
          href: string;
          id?: string | null;
        }[]
      | null;
  };
  closing: {
    heading: string;
    subtitle?: string | null;
    primaryButton: {
      label: string;
      href: string;
    };
  };
  meta?: {
    /**
     * Shown in the browser tab and as the clickable headline in search results. Falls back to the default page title if left blank.
     */
    title?: string | null;
    /**
     * Shown under the title in search results. Aim for roughly 150-160 characters. Falls back to the default description if left blank.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  tagline?: T;
  secondaryTagline?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        phoneLabel?: T;
        phoneHref?: T;
        tollFreeLabel?: T;
        tollFreeHref?: T;
        email?: T;
        address?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        primaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
        backgroundImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        backgroundImageInterval?: T;
      };
  showYou?:
    | T
    | {
        heading?: T;
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        cards?:
          | T
          | {
              title?: T;
              label?: T;
              labelColor?: T;
              description?: T;
              id?: T;
            };
      };
  ministryBuilt?:
    | T
    | {
        heading?: T;
        description?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        button?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  ministerProfile?:
    | T
    | {
        label?: T;
        name?: T;
        title?: T;
        bio?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  initiatives?:
    | T
    | {
        heading?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  governmentService?:
    | T
    | {
        heading?: T;
        description?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        images?:
          | T
          | {
              family?: T;
              laptop?: T;
              celebrating?: T;
            };
      };
  drawThreads?:
    | T
    | {
        heading?: T;
        description?: T;
        tags?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  countryFuture?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  textImageSections?:
    | T
    | {
        heading?: T;
        text?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        imagePosition?: T;
        id?: T;
      };
  mission?:
    | T
    | {
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  dualCta?:
    | T
    | {
        first?:
          | T
          | {
              heading?: T;
              description?: T;
              button?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
            };
        second?:
          | T
          | {
              heading?: T;
              description?: T;
              button?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
            };
      };
  policyAreas?:
    | T
    | {
        heading?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        policies?:
          | T
          | {
              label?: T;
              status?: T;
              href?: T;
              id?: T;
            };
      };
  departments?:
    | T
    | {
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              linkLabel?: T;
              href?: T;
              id?: T;
            };
      };
  ministerProfiles?:
    | T
    | {
        label?: T;
        name?: T;
        title?: T;
        bio?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        id?: T;
      };
  countryFuture?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress-page_select".
 */
export interface ProgressPageSelect<T extends boolean = true> {
  status?:
    | T
    | {
        heading?: T;
        description?: T;
        cards?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              color?: T;
              image?: T;
              id?: T;
            };
      };
  modernizeGovernment?:
    | T
    | {
        title?: T;
        description?: T;
        cards?:
          | T
          | {
              icon?: T;
              label?: T;
              labelColor?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  buildFutureReadiness?:
    | T
    | {
        title?: T;
        description?: T;
        cards?:
          | T
          | {
              icon?: T;
              label?: T;
              labelColor?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  developBahamianTalent?:
    | T
    | {
        title?: T;
        description?: T;
        backgroundImage?: T;
        cards?:
          | T
          | {
              icon?: T;
              label?: T;
              labelColor?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  driveNationalDevelopment?:
    | T
    | {
        title?: T;
        description?: T;
        cards?:
          | T
          | {
              icon?: T;
              label?: T;
              labelColor?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  countryFuture?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        pillarsHeading?: T;
        pillarsDescription?: T;
        footerText?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates-page_select".
 */
export interface UpdatesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  closing?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "get-involved-page_select".
 */
export interface GetInvolvedPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  categoriesSection?:
    | T
    | {
        heading?: T;
        categories?:
          | T
          | {
              icon?: T;
              image?: T;
              title?: T;
              description?: T;
              href?: T;
              id?: T;
            };
      };
  form?:
    | T
    | {
        formTitle?: T;
        illustrationImage?: T;
        notifications?:
          | T
          | {
              notificationEmail?: T;
              emailTemplate?:
                | T
                | {
                    logo?: T;
                    subject?: T;
                    heading?: T;
                    body?: T;
                    footer?: T;
                  };
              successMessage?: T;
            };
      };
  reachOut?:
    | T
    | {
        heading?: T;
        text?:
          | T
          | {
              text?: T;
              id?: T;
            };
        button?:
          | T
          | {
              label?: T;
              href?: T;
            };
        image?: T;
        imagePosition?: T;
      };
  followTheWork?:
    | T
    | {
        heading?: T;
        description?: T;
        backgroundImage?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              label?: T;
              href?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        secondaryCTA?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  officeInfo?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
        hours?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
      };
  enquiries?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        email?: T;
        id?: T;
      };
  followUs?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              label?: T;
              href?: T;
              id?: T;
            };
      };
  closing?:
    | T
    | {
        heading?: T;
        subtitle?: T;
        primaryButton?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}